spring:
  config:
    activate:
      on-profile: prod
  docker:
    compose:
      enabled: false

  neo4j:
    authentication:
      username: ${NEO4J_USERNAME:neo4j}
      password: ${NEO4J_PASSWORD:password}
    uri: ${NEO4J_URI:bolt://localhost:7687}

ai:
  embedding:
    base-url: ${EMBEDDING_BASE_URL:http://localhost:11434}
    model: ${EMBEDDING_MODEL:embeddinggemma:latest}
    timeout: 60s
  chat:
    base-url: ${CHAT_BASE_URL:https://api.groq.com/openai/v1}
    model: ${CHAT_MODEL:llama3-70b-8192}
    api-key: ${CHAT_API_KEY:your-api-key}
    timeout: 120s
