spring:
  config:
    activate:
      on-profile: local
  docker:
    compose:
      file: ../docker/compose.yaml
      lifecycle-management: start-and-stop
      readiness:
        tcp:
          read-timeout: 2m
