spring:
  config:
    activate:
      on-profile: prod
  docker:
    compose:
      enabled: false
  neo4j:
    uri: ${NEO4J_URI:bolt://localhost:7687}
    authentication:
      username: ${NEO4J_USERNAME}
      password: ${NEO4J_PASSWORD}
  ai:
    vectorstore:
      neo4j:
        initialize-schema: true
        database-name: ${NEO4J_DATABASE}
        index-name: course_embeddings
        embedding-dimension: 768
        distance-type: cosine
